### ISSUE TITLE
fix window size and scroll map

### ISSUE THREAD

**Issue by jmorwick** [mwsu-csmp/gg-pixi-client#2]

**Comment by sprine168** [comment]
Create a comment that shows I was here.

**Comment by little5words** [comment]
Push on 8/17 has a camera viewing the board with character centered  moves with player. Its still shows the door and bottom right corner tile. Camera moves around on board needs to be fixed to a spot but still show board movements.

**Comment by jmorwick** [comment]
current submits mostly resolve this issue. 

To complete this issue, we should prevent blank screen area when moving towards the edge of a board, and instead move the player's avatar off of the center.
